# Change these first
owner: interTwin-eu # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Rucio
    check: "tcp-ping"
    url: rucio-intertwin-testbed.desy.de
    port: 443
  - name: FTS
    check: "tcp-ping"
    url: fts-egi.cern.ch
    port: 8446
  - name: PaaS Orchestrator
    url: https://eosc-paas.cloud.ba.infn.it
  - name: JupyterHub_interlink
    url: https://jupyter-ukri.intertwin.fedcloud.eu/ 
  - name: EGI Check-in Demo
    url: https://aai-demo.egi.eu/
  - name: GRNET Cloud
    url: https://ui.cloud.grnet.gr/
  - name: UKRI Cloud
    url: https://openstack.stfc.ac.uk
  - name: OSCAR-GRNET
    url: https://oscar-grnet.intertwin.fedcloud.eu/
  - name: OSCAR-UKRI
    url: https://oscar-ukri.intertwin.fedcloud.eu/
  - name: MLFlow
    url: https://mlflow.intertwin.fedcloud.eu/signup 
  - name: SQAasS
    url: https://sqaaas.eosc-synergy.eu/
  - name: ALISE
    url: https://alise.data.kit.edu/
  - name: Container Registry
    url: https://registry.egi.eu/
  - name: dCache VEGA
    check: "tcp-ping"
    url: dcache.sling.si
    port: 2880
  - name: interLink VEGA
    check: "tcp-ping"
    url: intertwin.vega.izum.si
    port: 30443

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: interTwin Services Uptime
  introTitle: "**interTwin project uptime**"
  introMessage: Shows the avaiability of the services part of the interTwin DTE
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
